pipeline{
  agent any

  environment{
    DOCKER_HUB_LOGIN = credentials('5118029c-7738-4af3-81b1-9887f0edf750')
    DOCKER_REGISTRY = "https://index.docker.io/v1/"
    DOCKER_IMAGE_NAME = "munnakumar/demo"
  }

  parameters{
    choice(name: 'BUILD_NUMBER_CHOICE', choices: ['Auto', 'Manual'], description: 'Select the choice you wanna to increament the build number')
    string(name: 'MANUAL_BUILD_NUMBER', defaultValue: '1', description: 'Enter the build number')
  }

  stages{

    stage('Setup'){
      steps{
        script{
          getBuildNumber = {
            if(params.BUILD_NUMBER_CHOICE == "Auto")
            {
              echo "Auto ${env.BUILD_NUMBER}"
              return env.BUILD_NUMBER
            }
            echo "Manual ${env.MANUAL_BUILD_NUMBER}"
            return env.MANUAL_BUILD_NUMBER
          }
        }
      }
    }

    stage('Build'){
      steps{
        script{
          def BUILD_NUM = getBuildNumber()
          sh """ 
            set +x
            ls -a
            
            echo $DOCKER_HUB_LOGIN_PSW | docker login --username $DOCKER_HUB_LOGIN_USR --password-stdin ${DOCKER_REGISTRY}
            docker build --file ./WebApplication1/Dockerfile -t ${DOCKER_IMAGE_NAME}:${BUILD_NUM} .
            docker tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${BUILD_NUM} ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:latest 
            docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${BUILD_NUM}
            docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:latest

            ls -a
          """
        }
      }
    }

    stage('Test'){
      steps{
        echo 'Hello Testing'
      }
    }
  }
}
