name: weather Workflow

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - 'feature/*'
    
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            # registry : ghcr.io
            username: ${{ vars.GITHUB_USERNAME }}
            password: ${{ vars.GITHUB_PASSWORD  }}

        - name: Build and push image
          uses: docker/build-push-action@v3
          with:
            context: .
            push: true
            tags: {{ vars.GITHUB_USERNAME }}/solar-system:${{github.sha}}
